### ISSUE TITLE
Suspendable controller methods returning ResponseEntity are not handled

### ISSUE THREAD

**Issue by fabienmoritz** [konrad-kaminski/spring-kotlin-coroutine#14] opened 2018-02-15 15:21 UTC
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-ann-responseentity

The ResponseEntityResultHandler does not resolve the return type properly.

Example :
```kotlin

data class TestData(val value: String)

private val repo = mutableListOf<TestData>()

@RequestMapping("/testJson", produces = [MediaType.APPLICATION_JSON_UTF8_VALUE], consumes = [MediaType.APPLICATION_JSON_UTF8_VALUE])
@Controller
class JsonController {

    @GetMapping("/suspend/{value}")
    @ResponseBody
    suspend fun get(@PathVariable value: String) = repo.find { it.value == value }

// FAIL (IllegalStateException on ViewResolutionResultHandler because it is not handled by the ResponseEntityResultHandler)
    @PostMapping("/suspend")
    suspend fun createSuspend(@RequestBody value: TestData): ResponseEntity<TestData> {
        repo.add(value)
        delay(100)
        return ResponseEntity
                .created(URI("/testJson/suspend/${value.value}"))
                .body(value)
    }

// WORKS
    @PostMapping("/mono")
    fun create(@RequestBody value: TestData): Mono<ResponseEntity<TestData>> {
        repo.add(value)
        //delay(100)
        return Mono.just(ResponseEntity
                .created(URI("/testJson/suspend/${value.value}"))
                .body(value))
    }
}
```

**Comment by konrad-kaminski** [comment] 2018-02-19 10:55
This an [issue](https://jira.spring.io/browse/SPR-16515) in Spring Core with incorrect return type of a suspending functions. I created a PR for solving it. Once it's solved it should work fine.

In the meantime I'll try to find some workaround.

**Comment by konrad-kaminski** [comment] 2018-02-19 15:34
I'm closing this issue as this is a duplicate of #10. The workaround I mentioned can be found there.

**Closed by konrad-kaminski** 2018-02-19 15:34 UTC
